# -*- coding: utf-8 -*-
"""cv_at1_co1_q07.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWI_UM1J-5gpdSf8fHz2GIFilQaOu5XL
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a synthetic grayscale scene
img = np.zeros((250, 300), dtype=np.uint8)

# Sky gradient
for i in range(120):
    img[i, :] = 50 + i

# Ground
img[120:, :] = 180

# Mountain
pts = np.array([[50,120], [150,30], [250,120]], np.int32)
cv2.fillPoly(img, [pts], 120)

# Sun
cv2.circle(img, (230, 50), 25, 255, -1)

# Step 2: Reduce intensity resolution to 3-bit (8 gray levels)
quantized = (img // 32) * 32

# Step 3: Display results
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(img, cmap='gray')
plt.title("Original (8-bit)")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(quantized, cmap='gray')
plt.title("Quantized (3-bit)")
plt.axis('off')

plt.tight_layout()
plt.show()
