# -*- coding: utf-8 -*-
"""cv_co1_at1_q04.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eve4PBkgg8iswJGLFQN0PzSYYQpHGewX
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a synthetic medical scan image
img = np.zeros((300, 300), dtype=np.uint8)

# Simulated tissues with different densities
cv2.circle(img, (150, 150), 100, 80, -1)    # Soft tissue
cv2.circle(img, (150, 150), 60, 140, -1)    # Organ
cv2.circle(img, (120, 120), 20, 180, -1)    # Small lesion/tumor
cv2.circle(img, (190, 180), 15, 220, -1)    # Bright dense region

# Add smooth blur to mimic scan appearance
img = cv2.GaussianBlur(img, (9, 9), 0)

# -------- Pixel Resolution Reduction --------
low_pixel = cv2.resize(img, (75, 75), interpolation=cv2.INTER_AREA)
low_pixel = cv2.resize(low_pixel, (300, 300), interpolation=cv2.INTER_NEAREST)

# -------- Intensity Resolution Reduction --------
low_intensity = np.floor(img / 64) * 64      # Only 4 gray levels
low_intensity = low_intensity.astype(np.uint8)

# Display results
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title("Original Scan")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(low_pixel, cmap='gray')
plt.title("Low Pixel Resolution")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(low_intensity, cmap='gray')
plt.title("Low Intensity Resolution")
plt.axis('off')

plt.tight_layout()
plt.show()
